# Generated by Django 5.1.4 on 2025-01-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='genre',
        ),
        migrations.AddField(
            model_name='post',
            name='genres',
            field=models.ManyToManyField(to='myApp.genre'),
        ),
    ]
